// Generated by scripts/product.mjs from this repository's own source. Do not edit:
// `npm run generate` rewrites it, and scripts/product.test.mjs fails a build whose copy of
// it no longer matches what the sources say.
import type { Product } from './product-types'

export const product: Product = {
  "version": "0.1.0",
  "license": "MIT",
  "reads": [
    "list",
    "show",
    "stats",
    "brief",
    "deps",
    "delivered",
    "reversals",
    "budget",
    "non-goal list",
    "criterion list",
    "lint",
    "engines",
    "explain",
    "commands",
    "config",
    "pick",
    "block list",
    "section show",
    "claims",
    "unvalidated",
    "origin"
  ],
  "writes": [
    "add",
    "status",
    "ship",
    "retire",
    "defer",
    "resume",
    "section add",
    "section amend",
    "repair",
    "amend",
    "restate",
    "renumber",
    "validate"
  ],
  "languages": [
    "English",
    "Português (Brasil)"
  ],
  "scan": {
    "defaultDepth": 2,
    "depthCeiling": 6
  },
  "posture": {
    "contextIsolation": true,
    "nodeIntegration": false,
    "nodeIntegrationInWorker": false,
    "sandbox": true,
    "webSecurity": true,
    "webviewTag": false
  },
  "question": {
    "tools": [
      "Read",
      "Grep",
      "Glob"
    ],
    "turns": 24
  },
  "installers": {
    "win": [
      "nsis"
    ],
    "linux": [
      "AppImage"
    ],
    "mac": [
      "dmg"
    ]
  },
  "nonGoals": [
    {
      "title": "No Markdown parsed in this app",
      "why": "Every fact shown comes off a payload some verb printed, so a reader that parses a governed file or a field is the second implementation roadkeep exists to remove. Words an agent wrote for a person are drawn rendered and read for nothing."
    },
    {
      "title": "No write to a governed file",
      "why": "The app composes an argv and the command writes, so the parse-render round trip stays the tool's and two writers never share one file."
    },
    {
      "title": "No rule compiled into the client",
      "why": "No marker, id shape, limit, block label or governed filename as a literal: those are per-project configuration, and a copy of one in a reader breaks L6 from the outside instead of the inside."
    },
    {
      "title": "No engine the reader cannot name",
      "why": "Which copy of roadkeep answered is part of every answer; nothing is bundled and nothing is chosen silently, because three copies may differ and only naming which one wrote survives that."
    },
    {
      "title": "No field this app composes",
      "why": "A person types and an agent may author through the command; the app measures a draft against the budget and never writes a symptom, a why or a rationale, which is L4 held one surface out."
    },
    {
      "title": "No dates, estimates, velocity or burndown",
      "why": "A marker is maturity and not a schedule, so a chart of progress over time needs a field roadkeep refuses to store and this app would have to invent one to draw it."
    },
    {
      "title": "No git command run by this app",
      "why": "Staging, committing and pushing are the person's; the app prints the scope a claim declares and stops there, so a write nobody reviewed is never one click away."
    },
    {
      "title": "No account, no auth and no remote store in the desktop build",
      "why": "The service comes later as a transport swapped under the same client, and building identity now prices a user that does not exist against a design nobody has tested."
    },
    {
      "title": "No issue tracker, and no export to one",
      "why": "A backlog that lives in a service is one an agent cannot grep, which is roadkeep's own refusal; a view over the files is not a bridge out of them."
    }
  ]
}
