/**
 * Brazilian Portuguese, the second locale this build ships.
 *
 * A translation is a file and a file is a release: nothing here is read from disk, so adding
 * a language means editing this repository and shipping it, and a person cannot drop a
 * half-finished locale beside their settings and have the window speak it.
 *
 * The type is `Wording`, which is `Partial`, and that is not an accident about this file: a
 * translation in progress falls back per key and is worth shipping. What holds *this* one
 * complete is the suite, which runs `untranslated` over every locale the build lists — so a
 * new English string is a red run and not a Portuguese screen with an English sentence in
 * the middle of it.
 *
 * **The product name is not translated.** `app.name` is an identifier that happens to be a
 * word, and a locale that renamed it would be naming a different program.
 */

import type { Wording } from './wording'

/** The tag this file is written in, spelled as BCP-47 spells it. */
export const PT_BR_LOCALE = 'pt-BR'

export const PT_BR: Wording = {
  'app.name': 'roadkeep',

  'transport.absent': 'sem ponte - rodando como uma página comum de navegador',

  'portfolio.kicker': 'Portfólio',
  'portfolio.title': '{count} projetos nesta máquina',
  'portfolio.title.unknown': 'Projetos nesta máquina',
  'portfolio.tally': '{read} lidos · {pending} ainda lendo · {unreadable} ilegíveis',
  'portfolio.progress': '{stage}: {done} de {total}',
  'portfolio.stage.counting': 'contando cada backlog',
  'portfolio.stage.next': 'pedindo a próxima linha de cada um',
  'portfolio.asking': 'Procurando sob as raízes que as configurações nomeiam.',
  'portfolio.failed': 'A ponte não disse quais projetos existem: {reason}',
  'portfolio.none': 'Nenhum projeto foi encontrado sob as raízes que as configurações nomeiam.',
  'portfolio.none.hint':
    'Uma pasta com um roadkeep.toml sob uma dessas raízes aparece aqui na próxima vez que a janela perguntar.',
  'portfolio.filter.all': 'Todos {count}',
  'portfolio.filter.drifted': 'Verificação divergente {count}',
  'portfolio.filter.disagrees': 'Motor em desacordo {count}',
  'portfolio.filter.unreadable': 'Ilegíveis {count}',
  'portfolio.filter.label': 'Estreitar a lista',
  'portfolio.order': 'ordem: a do registro',
  'portfolio.column.project': 'Projeto',
  'portfolio.column.backlog': 'Pendências',
  'portfolio.column.next': 'Próxima linha pronta',
  'portfolio.column.gate': 'Verificação',
  'portfolio.column.engine': 'Motor',
  'portfolio.worktree': 'worktree do git',
  'portfolio.pending': 'ainda lendo',
  'portfolio.open': '{count} abertas',
  'portfolio.startable': '{startable} prontas para começar · {waiting} esperando',
  'portfolio.uncounted': '{count} não contadas',
  'portfolio.tier': 'nível: {tier}',
  'portfolio.next.none': 'nada pronto · {blocked} bloqueadas',
  'portfolio.next.missing': 'a próxima linha não chegou',
  'portfolio.gate.unknown': 'desconhecido',
  'portfolio.gate.clean': 'limpo',
  'portfolio.gate.drifted': 'divergente',
  'portfolio.gate.never': 'nunca rodou aqui',
  'portfolio.gate.findings': '{count} achados',
  'portfolio.gate.stale': 'desatualizado',
  'portfolio.engine.modified': 'árvore de trabalho',
  'portfolio.unreadable': 'ilegível',
  'portfolio.tried': 'o que foi tentado',
  'portfolio.kept': 'continua na lista',
  'portfolio.footnote':
    'Cada número nesta tela foi impresso por um verbo. Nada é somado entre projetos.',

  'project.back': 'Portfólio',
  'project.counts':
    '{open} abertas · {startable} prontas para começar · {waiting} esperando um requisito · {uncounted} não contadas',
  'project.opening': 'Abrindo o projeto.',
  'project.refused': 'Este projeto não abriu: {reason}',
  'project.roles': 'Arquivos governados',
  'project.blocks': 'Blocos',
  'project.block.finished': 'concluído',
  'project.filter.marker': 'marcador',
  'project.filter.requirement': 'requisito',
  'project.filter.note':
    'a prontidão é o que o deps respondeu para cada linha, nunca calculada aqui',
  'project.listing': 'Lendo as linhas.',
  'project.none': 'Nenhuma linha responde a este filtro.',
  'project.design.written': 'design escrito · §{ref}',
  'project.design.none': 'sem design ainda',
  'project.deps.none': 'sem dependências',
  'project.readiness.asking': 'perguntando',
  'project.waiting': 'esperando {ids}',
  'project.cycle': 'em ciclo com {ids}',
  'project.unheld': 'marcada, sem dono',
  'project.unheld.why': 'o marcador diz iniciada; o registro de claims não nomeia ninguém',
  'project.held': 'com {by}',
  'project.tab.unread': 'Este arquivo é governado e esta janela ainda não o lê.',
  'project.changelog.none': 'Nada foi entregue ainda.',
  'project.undone': 'desfeita por {by}',
  'project.decisions.none': 'Nenhuma decisão registrada ainda.',
  'project.decision.reasoning': 'o raciocínio',
  'project.decision.asking': 'Lendo a seção.',
  'project.decision.bare': 'Esta decisão não guarda uma seção própria.',
  'project.deferred.none': 'Nada foi posto de lado.',
  'project.deferred.order': 'Na ordem que o engine deu: {order}.',
  'project.deferred.since': 'posta de lado há {count} commits',
  'project.improvements.none': 'Nenhuma linha aberta tem design escrito ainda.',
  'project.read.failed': 'Este arquivo não respondeu: {reason}',
  'project.line.open': 'Abrir',
  'project.line.open.named': 'Abrir {id}',

  'task.opening': 'Abrindo a linha.',
  'task.refused': 'Esta linha não abriu: {reason}',
  'task.block': 'Bloco {block}',
  'task.shipped': 'entregue, e no registro de entregas',
  'task.copy': 'Copiar o brief',
  'task.copied': 'Copiado',
  'task.copy.failed': 'O brief não foi copiado: {reason}',
  'task.design.where': '§{anchor} · em {where}',
  'task.design.budget': '{taken} de {limit} {unit}',
  'task.design.over': '{taken} de {limit} {unit}, {over} além',
  'task.design.count': '{words} palavras',
  'task.design.face':
    'mostrado exatamente como o arquivo o quebra · nenhum Markdown é interpretado neste app',
  'task.design.none': 'Nenhum design foi escrito para esta linha.',
  'task.readiness': '{readiness} — a palavra é do engine, não deste app',
  'task.requires': 'precisa de {what}',
  'task.unblocks': 'entregar esta desbloqueia {count} de {of} linhas abertas',
  'task.underway': 'Em andamento',
  'task.underway.working': '{by} está nela, desde {since}',
  'task.underway.held': 'com {by}, desde {since}',
  'task.underway.started': 'iniciada, e nenhum claim sobre ela segue vivo',
  'task.underway.idle': 'não iniciada, e o registro de claims não nomeia ninguém',
  'task.underway.agree': 'o marcador e o registro concordam',
  'task.underway.disagree': 'o marcador e o registro discordam',
  'task.binds': 'O que prende esta linha · bloco {block}',
  'task.criteria.none': 'Este bloco não declara nenhum critério.',
  'task.criteria.elided': 'mais {count} critérios não listados',
  'task.quoted': 'Não-objetivos que este design cita',
  'task.bounds': 'Não-objetivos',
  'task.bounds.elided': 'mais {count} não listados',
  'task.paused': 'Esta linha foi posta de lado.',
  'task.paused.back': '{verb} {id} a traz de volta',
  'task.unfiled': 'Nada neste projeto carrega {id}.',
  'task.unknown': 'Não encontrada, numa leitura que não viu todas as linhas.',
  'task.handOver': 'Entregar ao Claude Code',
  'task.handing': 'Tomando a linha e iniciando a sessão.',
  'task.held.named': 'Com {by}, desde {since}, então nenhuma segunda sessão é oferecida.',
  'task.handOver.unready': 'O engine chama esta linha de {readiness}, então ela não foi tomada.',
  'task.handOver.refused': 'A linha não foi tomada: {reason}',
  'task.handOver.unavailable':
    'Nenhum Claude Code respondeu nesta máquina, então a linha não foi tomada. Tentado: {tried}',
  'task.handOver.withheld': 'A linha não foi entregue: {reason}',
  'task.session.open': 'Abrir a sessão',

  'session.opening': 'Procurando a sessão.',
  'session.missing': 'Esta janela não guarda nenhuma sessão com esse nome.',
  'session.stop': 'Parar a sessão',
  'session.state.starting': 'iniciando',
  'session.state.running': 'rodando',
  'session.state.done': 'concluída',
  'session.state.failed': 'falhou',
  'session.state.cancelled': 'parada',
  'session.state.unavailable': 'sem Claude Code',
  'session.claim': 'claim tomado: {from} → {to}',
  'session.handed': 'O que foi entregue',
  'session.handed.design': 'o design, {words} palavras',
  'session.handed.nodesign': 'nenhum design escrito',
  'session.handed.deps': '{count} dependências',
  'session.handed.criteria': '{count} critérios',
  'session.handed.bounds': '{count} não-objetivos',
  'session.handed.agent': 'iniciada com {command}, Claude Code {version}',
  'session.stream': 'O fluxo',
  'session.stream.empty': 'Nada foi escrito ainda.',
  'session.act.roadkeep': 'chamada ao roadkeep',
  'session.act.governed': 'toca {files}',
  'session.act.failed': 'falhou',
  'session.act.raw': 'a linha crua',
  'session.moved': 'O que mudou',
  'session.moved.none': 'Nada na linha mudou ainda.',
  'session.change.marker': 'marcador {from} → {to}',
  'session.change.design.written': 'design escrito',
  'session.change.design.deleted': 'design apagado',
  'session.change.shipped': 'entregue, e no registro de entregas',
  'session.change.symptom': 'sintoma reescrito',
  'session.change.why': 'porquê emendado',
  'session.change.depsAdded': 'dependências acrescentadas: {ids}',
  'session.change.depsDropped': 'dependências retiradas: {ids}',
  'session.change.left': 'a linha saiu: {said}',
  'session.result': 'sua última palavra: {result}',
  'session.files': 'Os arquivos governados',
  'session.file.never': 'ainda não escrito',
  'session.claims': 'Claims tomados em outras linhas',
  'session.claims.none': 'Nenhuma outra linha deste projeto está com alguém.',
  'session.claim.since': '{state}, desde {since}',

  'sessions.kicker': 'Sessões',
  'sessions.title': '{count} sessões iniciadas por esta janela',
  'sessions.title.none': 'Sessões iniciadas por esta janela',
  'sessions.none': 'Nenhuma sessão foi iniciada a partir desta janela.',
  'sessions.none.hint':
    'Entregar ao Claude Code numa linha inicia uma, e ela fica listada aqui enquanto esta janela roda.',
  'sessions.column.line': 'Linha',
  'sessions.column.project': 'Projeto',
  'sessions.column.state': 'Estado',
  'sessions.open': 'Abrir {id}',
  'sessions.footnote':
    'As sessões vivem com esta janela: o que está listado aqui é o que este processo iniciou e ainda guarda.',

  'filing.title': 'Registrar uma linha',
  'filing.about': 'Uma linha e o design que ela aponta, em um comando só.',
  'filing.id': 'esta seria a {id}',
  'filing.block': 'Bloco',
  'filing.marker': 'Marcador',
  'filing.deps': 'Dependências',
  'filing.deps.add': 'Acrescentar uma dependência',
  'filing.deps.none': 'sem dependências',
  'filing.deps.drop': 'Retirar {id}',
  'filing.symptom': 'Sintoma',
  'filing.symptom.about': 'O que não funciona, nunca o nome de uma correção.',
  'filing.why': 'Porquê',
  'filing.why.about': 'Uma frase, e ela termina em ponto.',
  'filing.section': 'O design',
  'filing.section.title': 'O título dele',
  'filing.section.body': 'A prosa',
  'filing.counter': 'restam {left} de {allowed}',
  'filing.counter.aim': 'restam {left} de {allowed}, {room} até o alvo',
  'filing.counter.over': '{taken} de {allowed}, {over} além',
  'filing.counter.line': 'o que a linha renderizada deixa',
  'filing.structure': '{structure} de {max} é estrutura, sobrando {prose} para a prosa',
  'filing.words': '{taken} de {limit} {unit}',
  'filing.pricing': 'Perguntando o que esta linha deixa.',
  'filing.bounds': 'O que prende uma linha aqui',
  'filing.bounds.none': 'Este projeto não declara nenhum não-objetivo.',
  'filing.command': 'O comando, antes de rodar',
  'filing.copy': 'Copiar o comando',
  'filing.copied': 'Copiado',
  'filing.save': 'Registrar',
  'filing.saving': 'Registrando a linha.',
  'filing.wrote': 'Registrada como {id}, e esta tela vai atrás dela.',
  'filing.refused': 'O engine recusou: {said}',
  'filing.failed': 'O comando não rodou: {reason}',
  'filing.unreadable': 'A resposta não pôde ser lida: {reason}',
  'filing.doors': 'O que o engine oferece no lugar',

  'door.writes': 'escreve um arquivo governado',
  'door.take': 'Aceitar',
  'door.blank': 'o que vai onde o engine deixou em branco',

  'gate.title': 'A verificação',
  'gate.about': 'O que os arquivos governados dizem de si, e o que encerra cada achado.',
  'gate.run': 'Rodar a verificação',
  'gate.running': 'Rodando a verificação.',
  'gate.failed': 'A verificação não rodou: {reason}',
  'gate.unreadable': 'A verificação respondeu algo que esta versão não sabe ler: {reason}',
  'gate.clean': 'Limpo: {lines} linhas e {sections} seções, e nada a responder.',
  'gate.problems': '{problems} achados em {lines} linhas e {sections} seções',
  'gate.notes': 'Dito sem reprovar por isso',
  'gate.doors': 'O que encerra isto',
  'gate.doors.none': 'Nada aqui encerra este achado sozinho.',
  'gate.decision': 'Decida isto primeiro: {decision}',
  'gate.awaits': 'Depende de {awaits}',
  'gate.sequence': 'Nesta ordem, não é uma escolha.',
  'gate.checked': 'Lido: {checked}',

  'roots.label': 'Raízes',
  'roots.add': 'Adicionar uma raiz',
  'roots.rescan': 'Reescanear as raízes',
  'roots.choose': 'Escolha uma pasta onde procurar',
  'roots.depth': '{depth} níveis abaixo',
  'roots.missing': 'ausente',
  'roots.remove': 'Parar de procurar em {path}',
  'roots.none': 'Nenhuma raiz foi nomeada ainda, então nada é percorrido.',
  'roots.none.hint': 'Adicione uma raiz para nomear uma pasta onde esta janela pode procurar.',
  'roots.unsaved': 'As raízes não puderam ser salvas: {reason}',

  'settings.reset': 'Algumas configurações não puderam ser lidas e voltaram aos valores padrão.',
  'settings.unsaved': 'Essa escolha não pôde ser salva, então a próxima abertura não a terá.',

  'settings.lost.unparsable': '{file} não pode ser lido como JSON, então ele fica intacto',
  'settings.lost.file':
    'o arquivo de configurações não é um objeto, então tudo voltou ao valor padrão',
  'settings.lost.unversioned':
    'o arquivo de configurações não diz sua versão, então ele é lido como esta build escreve',
  'settings.lost.version':
    'o arquivo de configurações é da versão {found} e esta build lê {reads}, então ele fica intacto',
  'settings.lost.roots': 'as raízes não eram uma lista, então nenhuma foi lida',
  'settings.lost.dropped': '{count} raiz(es) não puderam ser lidas e foram descartadas',
  'settings.lost.skip': 'a lista de nomes a ignorar não era uma lista, então vale a lista padrão',
  'settings.lost.width': 'a largura do pool não era um número inteiro, então voltou para {width}',
  'settings.lost.theme': 'o fundo não é um que esta build conhece, então voltou para {theme}',
  'settings.lost.locale': 'o idioma não era um texto, então o sistema decide',

  'shell.home': 'Início',
  'shell.palette': 'Encontre uma linha em qualquer backlog',
  'shell.shortcuts': 'Atalhos de teclado',
  'shell.notices': 'Notificações',

  'menu.help': 'Ajuda',
  'update.check': 'Procurar atualizações…',
  'update.title': 'Atualizações',
  'update.newer': 'Você está na {current}. A mais recente publicada é a {latest}.',
  'update.current': 'Você está na {current}, que é a mais recente publicada.',
  'update.ahead': 'Você está na {current}, que está à frente da mais nova publicada, a {latest}.',
  'update.none': 'Você está na {current}. Nenhuma versão foi publicada ainda.',
  'update.failed': 'Você está na {current}. A verificação não obteve resposta: {reason}',
  'update.open': 'Abrir a página da versão',
  'update.close': 'Fechar',

  'ground.system': 'fundo: seguindo o sistema',
  'ground.light': 'fundo: claro',
  'ground.dark': 'fundo: escuro',
  'ground.action': 'Mudar o fundo',
}
