/**
 * Brazilian Portuguese, the second locale this build ships.
 *
 * A translation is a file and a file is a release: nothing here is read from disk, so adding
 * a language means editing this repository and shipping it, and a person cannot drop a
 * half-finished locale beside their settings and have the window speak it.
 *
 * The type is `Wording`, which is `Partial`, and that is not an accident about this file: a
 * translation in progress falls back per key and is worth shipping. What holds *this* one
 * complete is the suite, which runs `untranslated` over every locale the build lists — so a
 * new English string is a red run and not a Portuguese screen with an English sentence in
 * the middle of it.
 *
 * **The product name is not translated.** `app.name` is an identifier that happens to be a
 * word, and a locale that renamed it would be naming a different program.
 */

import type { Wording } from './wording'

/** The tag this file is written in, spelled as BCP-47 spells it. */
export const PT_BR_LOCALE = 'pt-BR'

export const PT_BR: Wording = {
  'app.name': 'roadkeep',

  'transport.absent': 'sem ponte - rodando como uma página comum de navegador',

  'counts.read': '{count} lidos',
  'counts.read.one': '{count} lido',
  'counts.pending': '{count} ainda lendo',
  'counts.unreadable': '{count} ilegíveis',
  'counts.unreadable.one': '{count} ilegível',
  'counts.open': '{count} abertas',
  'counts.open.one': '{count} aberta',
  'counts.startable': '{count} prontas para começar',
  'counts.startable.one': '{count} pronta para começar',
  'counts.waiting': '{count} esperando',
  'counts.requirement': '{count} esperando um requisito',
  'counts.uncounted': '{count} não contadas',
  'counts.uncounted.one': '{count} não contada',
  'counts.blocked': '{count} bloqueadas',
  'counts.blocked.one': '{count} bloqueada',
  'counts.lines': '{count} linhas',
  'counts.lines.one': '{count} linha',
  'counts.sections': '{count} seções',
  'counts.sections.one': '{count} seção',

  'counts.remembered.one': '{count} do último início',

  'portfolio.kicker': 'Portfólio',
  'portfolio.title': '{count} projetos nesta máquina',
  'portfolio.title.one': '{count} projeto nesta máquina',
  'portfolio.title.unknown': 'Projetos nesta máquina',
  'portfolio.progress': '{stage}: {done} de {total}',
  'portfolio.stage.counting': 'contando cada backlog',
  'portfolio.stage.next': 'pedindo a próxima linha de cada um',
  'portfolio.asking': 'Procurando sob as raízes que as configurações nomeiam.',
  'portfolio.failed': 'A ponte não disse quais projetos existem: {reason}',
  'portfolio.none': 'Nenhum projeto foi encontrado sob as raízes que as configurações nomeiam.',
  'portfolio.none.hint':
    'Uma pasta com um roadkeep.toml sob uma dessas raízes aparece aqui na próxima vez que a janela perguntar.',
  'portfolio.filter.all': 'Todos {count}',
  'portfolio.filter.drifted': 'Verificação reprovada {count}',
  'portfolio.filter.disagrees': 'Motor em desacordo {count}',
  'portfolio.filter.unreadable': 'Ilegíveis {count}',
  'portfolio.filter.label': 'Estreitar a lista',
  'portfolio.order.record': 'ordem: a do registro',
  'portfolio.order.name-ascending': 'ordem: nome, de A a Z',
  'portfolio.order.name-descending': 'ordem: nome, de Z a A',
  'portfolio.order.open-descending': 'ordem: mais linhas abertas primeiro',
  'portfolio.order.open-ascending': 'ordem: menos linhas abertas primeiro',
  'portfolio.column.project': 'Projeto',
  'portfolio.column.backlog': 'Pendências',
  'portfolio.column.next': 'Próxima linha pronta',
  'portfolio.column.gate': 'Verificação',
  'portfolio.column.engine': 'Motor',
  'portfolio.worktree': 'worktree do git',
  'portfolio.remembered': 'do último início',
  'counts.remembered': '{count} do último início',
  'portfolio.pending': 'ainda lendo',
  'portfolio.tier': 'nível: {tier}',
  'portfolio.next.none': 'nada pronto',
  'portfolio.next.missing': 'a próxima linha não chegou',
  'portfolio.gate.unknown': 'desconhecido',
  'portfolio.gate.clean': 'limpo',
  'portfolio.gate.drifted': 'reprovada',
  'portfolio.gate.never': 'nunca rodou aqui',
  'portfolio.gate.findings': '{count} achados',
  'portfolio.gate.findings.one': '{count} achado',
  'portfolio.gate.open': 'Abrir a verificação de {name}: {counted}',
  'portfolio.gate.stale': 'desatualizado',
  'portfolio.engine.modified': 'árvore de trabalho',
  'portfolio.unreadable': 'ilegível',
  'portfolio.tried': 'o que foi tentado',
  'portfolio.kept': 'continua na lista',
  'portfolio.footnote':
    'Cada número nesta tela foi impresso por um verbo. Nada é somado entre projetos.',

  'project.back': 'Portfólio',
  'project.opening': 'Abrindo o projeto.',
  'project.refused': 'Este projeto não abriu: {reason}',
  'project.tabs': 'Este projeto',
  'palette.lines': 'Linhas',
  'palette.lines.partial': 'Linhas — {searched} de {total} backlogs pesquisados',
  'project.blocks': 'Blocos',
  'project.block.finished': 'concluído',
  'project.filter.marker': 'marcador',
  'project.filter.readiness': 'Prontidão',
  'project.filter.startable': 'Só as que dá para começar',
  'project.filter.requirement': 'requisito',
  'project.filter.note':
    'a prontidão é o que o deps respondeu para cada linha, nunca calculada aqui',
  'project.listing': 'Lendo as linhas.',
  'project.none': 'Nenhuma linha responde a este filtro.',
  'project.design.written': 'design escrito · §{ref}',
  'project.design.none': 'sem design ainda',
  'project.deps.none': 'sem dependências',
  'project.unheld': 'marcada, sem dono',
  'project.unheld.why': 'o marcador diz iniciada; o registro de claims não nomeia ninguém',
  'project.held': 'com {by}',
  'project.tab.unread': 'Este arquivo é governado e esta janela ainda não o lê.',
  'project.changelog.none': 'Nada foi entregue ainda.',
  'project.undone': 'desfeita por {by}',
  'project.decisions.none': 'Nenhuma decisão registrada ainda.',
  'project.decision.reasoning': 'o raciocínio',
  'project.decision.asking': 'Lendo a seção.',
  'project.decision.bare': 'Esta decisão não guarda uma seção própria.',
  'project.deferred.none': 'Nada foi posto de lado.',
  'project.deferred.order': 'Na ordem que o engine deu: {order}.',
  'project.deferred.since': 'posta de lado há {count} commits',
  'project.deferred.since.one': 'posta de lado há {count} commit',
  'project.improvements.none': 'Nenhuma linha aberta tem design escrito ainda.',
  'project.read.failed': 'Este arquivo não respondeu: {reason}',
  'project.line.open': 'Abrir',
  'project.line.open.named': 'Abrir {id}',

  'task.opening': 'Abrindo a linha.',
  'task.refused': 'Esta linha não abriu: {reason}',
  'task.block': 'Bloco {block}',
  'task.shipped': 'entregue, e no registro de entregas',
  'task.copy': 'Copiar o brief',
  'task.copied': 'Copiado',
  'task.copy.failed': 'O brief não foi copiado: {reason}',
  'task.design.where': '§{anchor} · em {where}',
  'task.design.budget': '{taken} de {limit} {unit}',
  'task.design.over': '{taken} de {limit} {unit}, {over} além',
  'task.design.count': '{count} palavras',
  'task.design.count.one': '{count} palavra',
  'task.design.face':
    'mostrado exatamente como o arquivo o quebra · nenhum Markdown é interpretado neste app',
  'task.design.none': 'Nenhum design foi escrito para esta linha.',
  'task.readiness': '{readiness} — a palavra é do engine, não deste app',
  'task.requires': 'precisa de {what}',
  'task.dep.open': 'Abrir {id}',
  'task.unblocks': 'entregar esta desbloqueia {count} de {of} linhas abertas',
  'task.underway': 'Em andamento',
  'task.underway.working': '{by} está nela, desde {since}',
  'task.underway.held': 'com {by}, desde {since}',
  'task.underway.started': 'iniciada, e nenhum claim sobre ela segue vivo',
  'task.underway.idle': 'não iniciada, e o registro de claims não nomeia ninguém',
  'task.underway.agree': 'o marcador e o registro concordam',
  'task.underway.disagree': 'o marcador e o registro discordam',
  'task.binds': 'O que prende esta linha · bloco {block}',
  'task.criteria.none': 'Este bloco não declara nenhum critério.',
  'task.criteria.own': 'O que esta linha precisa verificar',
  'task.criteria.folded': 'de {id}',
  'task.criteria.elided': 'mais {count} critérios não listados',
  'task.criteria.elided.one': 'mais {count} critério não listado',
  'task.quoted': 'Não-objetivos que este design cita',
  'task.bounds': 'Não-objetivos',
  'task.bounds.elided': 'mais {count} não listados',
  'task.bounds.elided.one': 'mais {count} não listado',
  'task.paused': 'Esta linha foi posta de lado.',
  'task.paused.back': '{verb} {id} a traz de volta',
  'task.unfiled': 'Nada neste projeto carrega {id}.',
  'task.unknown': 'Não encontrada, numa leitura que não viu todas as linhas.',
  'task.handOver': 'Entregar ao Claude Code',
  'task.handing': 'Tomando a linha e iniciando a sessão.',
  'task.held.named': 'Com {by}, desde {since}, então nenhuma segunda sessão é oferecida.',
  'task.handOver.unready': 'O engine chama esta linha de {readiness}, então ela não foi tomada.',
  'task.handOver.refused': 'A linha não foi tomada: {reason}',
  'task.handOver.unavailable':
    'Nenhum Claude Code respondeu nesta máquina, então a linha não foi tomada. Tentado: {tried}',
  'task.handOver.withheld': 'A linha não foi entregue: {reason}',
  'task.session.open': 'Abrir a sessão',

  'session.opening': 'Procurando a sessão.',
  'session.missing': 'Esta janela não guarda nenhuma sessão com esse nome.',
  'session.stop': 'Parar a sessão',
  'session.state.starting': 'iniciando',
  'session.state.running': 'rodando',
  'session.state.asking': 'pede permissão',
  'session.state.done': 'turno encerrado',
  'session.state.waiting': 'esperando você',
  'session.state.unshipped': 'encerrou sem entregar',
  'session.state.failed': 'falhou',
  'session.state.cancelled': 'parada',
  'session.state.unavailable': 'sem Claude Code',
  'session.claim': 'claim tomado: {from} → {to}',
  'session.handed': 'O que foi entregue',
  'session.handed.finding': 'O achado entregue',
  'session.handed.design': 'o design, {count} palavras',
  'session.handed.design.one': 'o design, {count} palavra',
  'session.handed.nodesign': 'nenhum design escrito',
  'session.handed.deps': '{count} dependências',
  'session.handed.deps.one': '{count} dependência',
  'session.handed.criteria': '{count} critérios',
  'session.handed.criteria.one': '{count} critério',
  'session.handed.bounds': '{count} não-objetivos',
  'session.handed.bounds.one': '{count} não-objetivo',
  'session.handed.agent': 'iniciada com {command}, Claude Code {version}',
  'session.card.grip': 'Mover o cartão “{card}”',
  'session.card.role': 'cartão móvel',
  'session.card.instructions':
    'Pressione Espaço para pegar o cartão, as setas para escolher onde ele vai, e então Espaço para soltá-lo ali ou Esc para deixá-lo onde estava.',
  'session.card.lifted': 'Cartão “{card}” pego.',
  'session.card.at.left': '“{card}”: barra lateral esquerda, posição {place}.',
  'session.card.at.right': '“{card}”: barra lateral direita, posição {place}.',
  'session.card.dropped.left':
    'Cartão “{card}” solto na barra lateral esquerda, na posição {place}.',
  'session.card.dropped.right':
    'Cartão “{card}” solto na barra lateral direita, na posição {place}.',
  'session.card.back': 'O cartão “{card}” voltou para onde estava.',
  'session.stream': 'O fluxo',
  'session.stream.empty': 'Nada foi escrito ainda.',
  'session.follow': 'Ir para o fim',
  'session.follow.since': 'Ir para o fim, {count} novos',
  'session.follow.since.one': 'Ir para o fim, {count} novo',
  'session.notes.folded': '{count} notas de sistema ocultas',
  'session.notes.folded.one': '{count} nota de sistema oculta',
  'session.act.roadkeep': 'chamada ao roadkeep',
  'session.act.governed': 'toca {files}',
  'session.act.failed': 'falhou',
  'session.act.raw': 'a linha crua',
  'session.moved': 'O que mudou',
  'session.moved.none': 'Nada na linha mudou ainda.',
  'session.change.marker': 'marcador {from} → {to}',
  'session.change.design.written': 'design escrito',
  'session.change.design.deleted': 'design apagado',
  'session.change.shipped': 'entregue, e no registro de entregas',
  'session.change.symptom': 'sintoma reescrito',
  'session.change.why': 'porquê emendado',
  'session.change.depsAdded': 'dependências acrescentadas: {ids}',
  'session.change.depsDropped': 'dependências retiradas: {ids}',
  'session.change.left': 'a linha saiu: {said}',
  'session.result': 'Sua última palavra',
  'session.prose.wide': 'Rola para o lado',
  'session.prose.task.done': 'feito',
  'session.prose.task.open': 'não feito',
  'session.reply': 'Responder à sessão',
  'session.reply.send': 'Enviar a resposta',
  'session.reply.sending': 'Retomando a sessão.',
  'session.reply.held': 'Com {by}, desde {since}, então a sessão não foi retomada.',
  'session.reply.refused':
    'A linha não respondeu ao brief, então a sessão não foi retomada: {reason}',
  'session.reply.unavailable':
    'Nenhum Claude Code respondeu aqui, então a sessão não foi retomada. Tentado: {tried}',
  'session.reply.withheld': 'A resposta não foi enviada: {reason}',
  'session.grant.title': 'Negadas, e suas para liberar no próximo turno',
  'session.grant.allow': 'Liberar no próximo turno: {tool}',
  'session.grant.call': 'a chamada',
  'session.grant.reply': 'Liberado para este turno: {tools}. Pode seguir.',
  'session.ask.title': 'Esperando sua permissão',
  'session.ask.asked': 'pergunta',
  'session.ask.once': 'Permitir esta chamada',
  'session.ask.session': 'Permitir nesta sessão',
  'session.ask.decline': 'Recusar',
  'session.ask.grants': 'Nesta sessão, ela oferece: {grants}',
  'session.ask.open': 'Esperando sua resposta, abaixo do fluxo.',
  'session.ask.answered.once': 'Você permitiu esta chamada.',
  'session.ask.answered.session': 'Você permitiu nesta sessão.',
  'session.ask.answered.decline': 'Você recusou.',
  'session.ask.withdrawn': 'A sessão retirou a pergunta.',
  'session.ask.unanswered': 'A sessão terminou sem resposta.',
  'session.ask.withheld': 'A resposta não foi enviada: {reason}',
  'session.edited': 'Os arquivos que ela editou',
  'session.edited.about':
    'Nomeados pelas próprias chamadas da sessão; o disco diz como cada um está.',
  'session.edited.none': 'A sessão ainda não editou nenhum arquivo.',
  'session.edited.calls': '{count} edições',
  'session.edited.calls.one': '{count} edição',
  'session.edited.governed': 'governado',
  'session.edited.failed': 'a última edição falhou',
  'session.edited.changed': 'alterado no disco {when}',
  'session.edited.unchanged': 'inalterado no disco desde o início da sessão',
  'session.edited.missing': 'não está no disco',
  'session.edited.outside': 'fora deste projeto, não conferido',
  'session.edited.disagrees': 'o disco discorda',
  'session.edited.open': 'Abrir {path}',
  'session.file.reading': 'Lendo o arquivo.',
  'session.file.reload': 'Ler de novo',
  'session.file.lines': '{count} linhas, como o disco o guarda agora',
  'session.file.lines.one': '{count} linha, como o disco o guarda agora',
  'session.file.edits': 'O que a sessão mudou',
  'session.file.edit.act': 'ato {seq}',
  'session.file.edit.replaced': 'substituiu',
  'session.file.edit.put': 'colocou',
  'session.file.edit.wrote': 'escreveu o arquivo inteiro',
  'session.file.edit.found': 'está no arquivo',
  'session.file.edit.gone': 'não está no arquivo agora',
  'session.file.edit.folded': '{count} linhas',
  'session.file.edit.folded.one': '{count} linha',
  'file.refused.no-session':
    'Esta janela não iniciou nenhuma sessão com esse nome, então não há projeto onde ler o arquivo.',
  'file.refused.outside': 'O arquivo está fora deste projeto, então a janela não o lê.',
  'file.refused.missing': 'Não há arquivo nesse caminho agora.',
  'file.refused.unreadable':
    'Há algo nesse caminho, e não é um arquivo que esta janela consiga ler.',
  'file.refused.too-large':
    'O arquivo tem {bytes} bytes, além dos {ceiling} que esta janela lê. Abra-o em um editor.',
  'file.refused.not-text': 'O arquivo não é texto, então a janela não o desenha.',
  'session.disk': 'Mudou no disco enquanto ela rodava',
  'session.disk.about':
    'Arquivos que mudaram no projeto enquanto a sessão rodava e que nenhuma chamada de edição nomeou. O que mais escreveu nesse tempo também está aqui.',
  'session.disk.none': 'Nenhum outro arquivo do projeto mudou enquanto a sessão rodava.',
  'session.disk.moves': '{count} mudanças',
  'session.disk.moves.one': '{count} mudança',
  'session.disk.beyond': 'mais {count} não listados',
  'session.disk.beyond.one': 'mais {count} não listado',
  'session.files': 'Os arquivos governados',
  'session.file.never': 'ainda não escrito',
  'session.claims': 'Claims tomados em outras linhas',
  'session.claims.none': 'Nenhuma outra linha deste projeto está com alguém.',
  'session.claim.since': '{state}, desde {since}',

  'sessions.kicker': 'Sessões',
  'sessions.title': '{count} sessões iniciadas por esta janela',
  'sessions.title.one': '{count} sessão iniciada por esta janela',
  'sessions.title.none': 'Sessões iniciadas por esta janela',
  'sessions.none': 'Nenhuma sessão foi iniciada a partir desta janela.',
  'sessions.none.hint':
    'Entregar ao Claude Code numa linha inicia uma, e ela fica listada aqui enquanto esta janela roda.',
  'sessions.column.line': 'Linha',
  'sessions.column.project': 'Projeto',
  'sessions.column.state': 'Estado',
  'sessions.open': 'Abrir {id}',
  'sessions.footnote':
    'As sessões vivem com esta janela: o que está listado aqui é o que este processo iniciou e ainda guarda.',

  'filing.title': 'Registrar uma linha',
  'filing.about': 'Uma linha e o design que ela aponta, em um comando só.',
  'filing.id': 'esta seria a {id}',
  'filing.block': 'Bloco',
  'filing.marker': 'Marcador',
  'filing.deps': 'Dependências',
  'filing.deps.add': 'Acrescentar uma dependência',
  'filing.deps.none': 'sem dependências',
  'filing.deps.drop': 'Retirar {id}',
  'filing.symptom': 'Sintoma',
  'filing.symptom.about': 'O que não funciona, nunca o nome de uma correção.',
  'filing.why': 'Porquê',
  'filing.why.about': 'Uma frase, e ela termina em ponto.',
  'filing.section': 'O design',
  'filing.section.title': 'O título dele',
  'filing.section.body': 'A prosa',
  'filing.counter': 'restam {left} de {allowed}',
  'filing.counter.aim': 'restam {left} de {allowed}, {room} até o alvo',
  'filing.counter.over': '{taken} de {allowed}, {over} além',
  'filing.counter.line': 'o que a linha renderizada deixa',
  'filing.structure': '{structure} de {max} é estrutura, sobrando {prose} para a prosa',
  'filing.words': '{taken} de {limit} {unit}',
  'filing.pricing': 'Perguntando o que esta linha deixa.',
  'filing.near': 'O que o bloco {block} já tem',
  'filing.near.none': 'Nada neste bloco está perto disto ainda.',
  'filing.near.open': 'aberta',
  'filing.near.shipped': 'entregue',
  'filing.near.order': 'Do mais próximo ao menos. Não há nota: leia e julgue.',
  'filing.bounds': 'O que prende uma linha aqui',
  'filing.bounds.none': 'Este projeto não declara nenhum não-objetivo.',
  'filing.command': 'O comando, antes de rodar',
  'filing.copy': 'Copiar o comando',
  'filing.copied': 'Copiado',
  'filing.save': 'Registrar',
  'filing.saving': 'Registrando a linha.',
  'filing.wrote': 'Registrada como {id}, e esta tela vai atrás dela.',
  'filing.refused': 'O engine recusou: {said}',
  'filing.failed': 'O comando não rodou: {reason}',
  'filing.unreadable': 'A resposta não pôde ser lida: {reason}',
  'filing.doors': 'O que o engine oferece no lugar',

  'door.writes': 'escreve um arquivo governado',
  'door.take': 'Executar conserto',
  'door.blank': 'o que vai onde o engine deixou em branco',
  'door.body': 'o texto que esta porta escreve, que o engine lê da entrada padrão',
  'door.handOver': 'Entregar ao Claude Code',
  'door.handing': 'Iniciando uma sessão.',
  'door.handed': 'Abrir a sessão que foi iniciada.',
  'door.failed': 'O conserto não rodou: {reason}',

  'gate.title': 'A verificação',
  'gate.about': 'O que os arquivos governados dizem de si, e o que encerra cada achado.',
  'gate.run': 'Rodar a verificação',
  'gate.running': 'Rodando a verificação.',
  'gate.running.taken': '{taken}s dos {ceiling}s que ela tem.',
  'gate.failed': 'A verificação não rodou: {reason}',
  'gate.unreadable': 'A verificação respondeu algo que esta versão não sabe ler: {reason}',
  'gate.held.clean': 'Limpo quando rodou pela última vez.',
  'gate.held.drifted': '{count} achados quando rodou pela última vez.',
  'gate.held.drifted.one': '{count} achado quando rodou pela última vez.',
  'gate.taken': 'Última rodada {taken}.',
  'gate.never': 'Ainda não rodou nesta janela.',
  'gate.stale': 'Os arquivos mudaram depois, então isto é o que diziam antes.',
  'gate.clean': 'Limpo: {counted}, e nada a responder.',
  'gate.problems': '{count} achados em {counted}',
  'gate.problems.one': '{count} achado em {counted}',
  'gate.explain.asking': 'Perguntando o que este código significa.',
  'gate.explain.failed': 'Este build não disse o que este código significa.',
  'gate.notes': 'Dito sem reprovar por isso',
  'gate.doors': 'O que encerra isto',
  'gate.doors.none': 'Nada aqui encerra este achado sozinho.',
  'gate.decision': 'Decida isto primeiro: {decision}',
  'gate.awaits': 'Depende de {awaits}',
  'gate.sequence': 'Nesta ordem, não é uma escolha.',
  'gate.checked': 'Lido: {checked}',

  'backlog.over.narrows':
    '{count} linhas em {file} não foram listadas: esta leitura tem {characters} caracteres contra os {limit} que este projeto declara, então peça por {narrows}.',
  'backlog.over.narrows.one':
    '{count} linha em {file} não foi listada: esta leitura tem {characters} caracteres contra os {limit} que este projeto declara, então peça por {narrows}.',
  'backlog.over.whole':
    '{count} linhas em {file} não foram listadas: esta leitura tem {characters} caracteres contra os {limit} que este projeto declara, e nenhum bloco é pequeno o bastante para pedir sozinho.',
  'backlog.over.whole.one':
    '{count} linha em {file} não foi listada: esta leitura tem {characters} caracteres contra os {limit} que este projeto declara, e nenhum bloco é pequeno o bastante para pedir sozinho.',
  'backlog.refused':
    '{count} linhas em {file} têm um marcador que a gramática não aceitou, então nada as conta nem as escolhe.',
  'backlog.refused.one':
    '{count} linha em {file} tem um marcador que a gramática não aceitou, então nada a conta nem a escolhe.',
  'backlog.refused.reasons': 'O que o portão disse: {reasons}',

  'unreadable.not-json': '`{command}` respondeu algo que não é JSON.',
  'unreadable.shape':
    'A resposta não tem um formato que esta versão lê: {path} deveria ser {expected}, e era {got}.',
  'unreadable.declares':
    '`{verb}` foi recusado, então este projeto não declara nada que este app saiba ler.',
  'unreadable.behind':
    'A cópia que responde aqui é o roadkeep {version}, que não tem `{verb}`. Atualize esse checkout.',
  'unreadable.refused': '`{verb}` foi recusado.',
  'unreadable.ungoverned':
    'O engine que responde aqui diz que nenhum projeto roadkeep governa esta pasta.',
  'unreadable.nothing-offered':
    'Nada foi oferecido como engine para este projeto, então nada foi perguntado.',
  'unreadable.none-answered':
    'Nenhum candidato respondeu `engines --json`, então não se sabe qual roadkeep governa este projeto.',
  'unreadable.withheld': 'Esta pasta não é uma que a varredura das suas raízes encontrou.',

  'withheld.not-carried': 'Essa não é uma requisição que este app leva até o engine.',
  'withheld.no-such-door':
    'Nenhuma porta com esse nome está em oferta para este projeto. Leia de novo e use uma que a resposta traga.',
  'withheld.not-the-words': 'Uma porta recebe uma palavra para cada lacuna, e essa não era.',
  'withheld.not-catalogued': '`{root}` não é um projeto que a varredura das suas raízes encontrou.',
  'withheld.not-open': '`{root}` não abriu, então a requisição não rodou: {why}',

  'roots.label': 'Raízes',
  'roots.add': 'Adicionar uma raiz',
  'roots.rescan': 'Reescanear as raízes',
  'roots.choose': 'Escolha uma pasta onde procurar',
  'roots.depth': '{count} níveis abaixo',
  'roots.depth.one': '{count} nível abaixo',
  'roots.missing': 'ausente',
  'roots.remove': 'Parar de procurar em {path}',
  'roots.deeper': 'Procurar um nível mais fundo em {path}',
  'roots.shallower': 'Procurar um nível menos fundo em {path}',
  'roots.none': 'Nenhuma raiz foi nomeada ainda, então nada é percorrido.',
  'roots.none.hint': 'Adicione uma raiz para nomear uma pasta onde esta janela pode procurar.',
  'roots.unsaved': 'As raízes não puderam ser salvas: {reason}',

  'settings.reset': 'Algumas configurações não puderam ser lidas e voltaram aos valores padrão.',
  'settings.unsaved': 'Essa escolha não pôde ser salva, então a próxima abertura não a terá.',
  'settings.kicker': 'Este aplicativo',
  'settings.title': 'Configurações',
  'settings.subtitle':
    'Cada escolha fica no arquivo de configurações deste aplicativo assim que é feita.',
  'settings.appearance': 'Aparência',
  'settings.appearance.about': 'Como esta janela aparece, e o idioma em que ela fala.',
  'settings.ground': 'Fundo',
  'settings.ground.system': 'Seguir o sistema',
  'settings.ground.light': 'Claro',
  'settings.ground.dark': 'Escuro',
  'settings.language': 'Idioma',
  'settings.sessions': 'Sessões',
  'settings.sessions.about':
    'Como o fluxo de uma sessão do Claude Code é desenhado enquanto ela trabalha.',
  'settings.notes': 'Notas de sistema',
  'settings.notes.shown': 'Mostrar cada uma',
  'settings.notes.hidden': 'Agrupar e contar',

  'settings.lost.unparsable': '{file} não pode ser lido como JSON, então ele fica intacto',
  'settings.lost.file':
    'o arquivo de configurações não é um objeto, então tudo voltou ao valor padrão',
  'settings.lost.unversioned':
    'o arquivo de configurações não diz sua versão, então ele é lido como esta build escreve',
  'settings.lost.version':
    'o arquivo de configurações é da versão {found} e esta build lê {reads}, então ele fica intacto',
  'settings.lost.roots': 'as raízes não eram uma lista, então nenhuma foi lida',
  'settings.lost.dropped': '{count} raízes não puderam ser lidas e foram descartadas',
  'settings.lost.dropped.one': '{count} raiz não pôde ser lida e foi descartada',
  'settings.lost.skip': 'a lista de nomes a ignorar não era uma lista, então vale a lista padrão',
  'settings.lost.width': 'a largura do pool não era um número inteiro, então voltou para {width}',
  'settings.lost.projectsAtOnce':
    'quantos projetos ler de uma vez não era um número inteiro, então a máquina decide',
  'settings.lost.theme': 'o fundo não é um que esta build conhece, então voltou para {theme}',
  'settings.lost.locale': 'o idioma não era um texto, então o sistema decide',
  'settings.lost.sessionNotes':
    'o modo de desenhar as notas de sistema de uma sessão não é um que esta build conhece, então toda nota é desenhada',
  'settings.lost.portfolioOrder':
    'a ordem do portfólio não é uma que esta build conhece, então ele abre na ordem do registro',
  'settings.lost.sessionLayout':
    'onde ficam os cartões de uma sessão não eram duas listas, então eles voltaram ao lugar de origem',

  'shell.home': 'Início',
  'shell.palette': 'Encontre uma linha em qualquer backlog',
  'shell.shortcuts': 'Atalhos de teclado',
  'shell.notices': 'Notificações',

  'menu.help': 'Ajuda',
  'update.check': 'Procurar atualizações…',
  'update.title': 'Atualizações',
  'update.newer': 'Você está na {current}. A mais recente publicada é a {latest}.',
  'update.current': 'Você está na {current}, que é a mais recente publicada.',
  'update.ahead': 'Você está na {current}, que está à frente da mais nova publicada, a {latest}.',
  'update.none': 'Você está na {current}. Nenhuma versão foi publicada ainda.',
  'update.failed': 'Você está na {current}. A verificação não obteve resposta: {reason}',
  'update.failed.status': 'O GitHub respondeu {status}.',
  'update.failed.not-json': 'O GitHub respondeu algo que não é JSON.',
  'update.failed.missing': 'A resposta não trazia {path}.',
  'update.failed.version': '{version} não é uma versão que dê para comparar.',
  'update.open': 'Abrir a página da versão',
  'update.close': 'Fechar',

  'ground.action': 'Mudar o fundo',
}
